### PR TITLE
Add girs of apache arrow 3.0.0

### PR DESCRIPTION
**Pull request by taozuhong**

### CODE REVIEW

**Comment by taozuhong** [comment]
@ricotz could you pls take sometime to review it?

**Comment by ricotz** [comment]
@taozuhong Do you think it is possible to have upstream build the corresponding Vala bindings?

**Comment by taozuhong** [comment]
Just release GObject introspection files only:
https://arrow.apache.org/docs/c_glib/

```bash
# https://arrow.apache.org/install/
sudo apt install -y -V libarrow-glib-dev # For GLib (C)
sudo yum install -y --enablerepo=epel arrow-glib-devel # For GLib (C)
sudo yum install -y --enablerepo=epel arrow-glib-devel # For GLib (C)
```

**Comment by ricotz** [comment]
Pushed as b202dd6ed98cb3e7c54354466397a13761e29e97

**Pull request closed without merging**
